//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clipy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clipy.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Histories.
        /// </summary>
        internal static string @__menu_title_Delete_Histories {
            get {
                return ResourceManager.GetString("__menu_title_Delete_Histories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string @__menu_title_Exit {
            get {
                return ResourceManager.GetString("__menu_title_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string @__menu_title_Settings {
            get {
                return ResourceManager.GetString("__menu_title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets.
        /// </summary>
        internal static string @__menu_title_Snippets {
            get {
                return ResourceManager.GetString("__menu_title_Snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name can not be empty!.
        /// </summary>
        internal static string @__message_box_Group_name_not_empty {
            get {
                return ResourceManager.GetString("__message_box_Group_name_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add snippet.
        /// </summary>
        internal static string @__message_box_message_add_snippet {
            get {
                return ResourceManager.GetString("__message_box_message_add_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        internal static string @__message_box_message_copied {
            get {
                return ResourceManager.GetString("__message_box_message_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the snippets in &quot;.
        /// </summary>
        internal static string @__message_box_message_delete_group_part_1 {
            get {
                return ResourceManager.GetString("__message_box_message_delete_group_part_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; group will be deleted.
        ///Are you sure?.
        /// </summary>
        internal static string @__message_box_message_delete_group_part_2 {
            get {
                return ResourceManager.GetString("__message_box_message_delete_group_part_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected snippet(s) will be deleted.
        ///Are you sure?.
        /// </summary>
        internal static string @__message_box_message_delete_snippets {
            get {
                return ResourceManager.GetString("__message_box_message_delete_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit snippet.
        /// </summary>
        internal static string @__message_box_message_edit_snippet {
            get {
                return ResourceManager.GetString("__message_box_message_edit_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group can not be empty..
        /// </summary>
        internal static string @__message_box_message_group_cannot_empty {
            get {
                return ResourceManager.GetString("__message_box_message_group_cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename group.
        /// </summary>
        internal static string @__message_box_message_Remane_group {
            get {
                return ResourceManager.GetString("__message_box_message_Remane_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to default values?.
        /// </summary>
        internal static string @__message_box_message_Reset_all {
            get {
                return ResourceManager.GetString("__message_box_message_Reset_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings..
        /// </summary>
        internal static string @__message_box_message_save_errors {
            get {
                return ResourceManager.GetString("__message_box_message_save_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        internal static string @__message_box_message_saved {
            get {
                return ResourceManager.GetString("__message_box_message_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet can not be empty..
        /// </summary>
        internal static string @__message_box_message_snippet_cannot_empty {
            get {
                return ResourceManager.GetString("__message_box_message_snippet_cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string @__message_box_title_delete_group_part_1 {
            get {
                return ResourceManager.GetString("__message_box_title_delete_group_part_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete snippets.
        /// </summary>
        internal static string @__message_box_title_delete_snippets {
            get {
                return ResourceManager.GetString("__message_box_title_delete_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string @__message_box_title_Remane {
            get {
                return ResourceManager.GetString("__message_box_title_Remane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        internal static string @__message_box_title_Reset_all {
            get {
                return ResourceManager.GetString("__message_box_title_Reset_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All clipboard histories will be deleted!!!
        ///Note: Snippets will not be affected.
        ///
        ///Are you sure?.
        /// </summary>
        internal static string @__message_box_Warn_Delete_Histories {
            get {
                return ResourceManager.GetString("__message_box_Warn_Delete_Histories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (multiple snippets selected.).
        /// </summary>
        internal static string @__window_content_multiple_snippests_selected {
            get {
                return ResourceManager.GetString("__window_content_multiple_snippests_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Name).
        /// </summary>
        internal static string @__window_content_No_Name {
            get {
                return ResourceManager.GetString("__window_content_No_Name", resourceCulture);
            }
        }
    }
}
