//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clipy {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clipy.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Histories 的本地化字符串。
        /// </summary>
        internal static string @__menu_title_Delete_Histories {
            get {
                return ResourceManager.GetString("__menu_title_Delete_Histories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string @__menu_title_Exit {
            get {
                return ResourceManager.GetString("__menu_title_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string @__menu_title_Settings {
            get {
                return ResourceManager.GetString("__menu_title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippets 的本地化字符串。
        /// </summary>
        internal static string @__menu_title_Snippets {
            get {
                return ResourceManager.GetString("__menu_title_Snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group name can not be empty! 的本地化字符串。
        /// </summary>
        internal static string @__message_box_Group_name_not_empty {
            get {
                return ResourceManager.GetString("__message_box_Group_name_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add snippet 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_add_snippet {
            get {
                return ResourceManager.GetString("__message_box_message_add_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied! 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_copied {
            get {
                return ResourceManager.GetString("__message_box_message_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All the snippets in &quot; 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_delete_group_part_1 {
            get {
                return ResourceManager.GetString("__message_box_message_delete_group_part_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; group will be deleted.
        ///Are you sure? 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_delete_group_part_2 {
            get {
                return ResourceManager.GetString("__message_box_message_delete_group_part_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected snippet(s) will be deleted.
        ///Are you sure? 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_delete_snippets {
            get {
                return ResourceManager.GetString("__message_box_message_delete_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit snippet 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_edit_snippet {
            get {
                return ResourceManager.GetString("__message_box_message_edit_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group can not be empty. 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_group_cannot_empty {
            get {
                return ResourceManager.GetString("__message_box_message_group_cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename group 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_Remane_group {
            get {
                return ResourceManager.GetString("__message_box_message_Remane_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset all settings to default values? 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_Reset_all {
            get {
                return ResourceManager.GetString("__message_box_message_Reset_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error saving settings. 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_save_errors {
            get {
                return ResourceManager.GetString("__message_box_message_save_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved! 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_saved {
            get {
                return ResourceManager.GetString("__message_box_message_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippet can not be empty. 的本地化字符串。
        /// </summary>
        internal static string @__message_box_message_snippet_cannot_empty {
            get {
                return ResourceManager.GetString("__message_box_message_snippet_cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete  的本地化字符串。
        /// </summary>
        internal static string @__message_box_title_delete_group_part_1 {
            get {
                return ResourceManager.GetString("__message_box_title_delete_group_part_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete snippets 的本地化字符串。
        /// </summary>
        internal static string @__message_box_title_delete_snippets {
            get {
                return ResourceManager.GetString("__message_box_title_delete_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string @__message_box_title_Remane {
            get {
                return ResourceManager.GetString("__message_box_title_Remane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to default 的本地化字符串。
        /// </summary>
        internal static string @__message_box_title_Reset_all {
            get {
                return ResourceManager.GetString("__message_box_title_Reset_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All clipboard histories will be deleted!!!
        ///Note: Snippets will not be affected.
        ///
        ///Are you sure? 的本地化字符串。
        /// </summary>
        internal static string @__message_box_Warn_Delete_Histories {
            get {
                return ResourceManager.GetString("__message_box_Warn_Delete_Histories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (multiple snippets selected.) 的本地化字符串。
        /// </summary>
        internal static string @__window_content_multiple_snippests_selected {
            get {
                return ResourceManager.GetString("__window_content_multiple_snippests_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (No Name) 的本地化字符串。
        /// </summary>
        internal static string @__window_content_No_Name {
            get {
                return ResourceManager.GetString("__window_content_No_Name", resourceCulture);
            }
        }
    }
}
